services:
  jenkins:
    build:
     context: ./jenkins
    container_name: vprojenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.listenAddress=0.0.0.0
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped
    volumes:
      - /usr/bin/docker:/usr/local/bin/docker
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_ssh_keys:/root/.ssh

  ssh-agent:
    image: jenkins/ssh-agent

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
  
  vproapp:
    build:
      context: ./app
    container_name: vproapp
    ports:
      - "8082:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 60s
      retries: 30
    networks:
      - app_network
      - server_network
 

  
  mysql:
    build:
      context: ./db
    container_name: db01
    ports: 
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_DATABASE=accounts
    networks:
      - app_network
      - server_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq01
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    networks:
      - app_network


  memcached:
    image: memcached:1.5
    container_name: mc01
    ports:
      - "11211:11211"
    networks:
      - app_network

  vproweb:
    build: 
      context: ./web
    container_name: vproweb
    ports:
      - "80:80"
    depends_on:
      - vproapp
    networks:
      - app_network

volumes:
  jenkins_home: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  sonarqube_logs: {}
  sonarqube_temp: {}
  nexus_data: {}
  appdata: {}
  vprodbdata: {}
  jenkins_ssh_keys: {}

networks:
  app_network:
  server_network:
    driver: bridge