services:
  jenkins:
    build:
     context: ./jenkins
    container_name: vprojenkins
    image: zarrcloud/vprofilejenkins
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djenkins.listenAddress=0.0.0.0
    volumes:
      - jenkins_home:/var/jenkins_home

  ssh-agent:
    image: jenkins/ssh-agent

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
  
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data

  app:
    image: vprocontainers/vprofileapp
    container_name: vproapp
    ports:
      - "8082:8080"

 

  
  mysql:
    build:
      context: ./db
    image: zarrcloud/vprofiledb
    container_name: vprodb
    ports: 
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=vprodbpass

  vproweb:
    build: 
      context: ./web
    image: zarrcloud/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
  

volumes:
  jenkins_home: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  sonarqube_logs: {}
  sonarqube_temp: {}
  nexus_data: {}
  appdata: {}
  vprodbdata: {}